### ISSUE TITLE
[10/06/22] Update Progress Functionality

### ISSUE THREAD

**Issue by anagudelogu** [anagudelogu/bookstore-react#9]
# [10/06/22]

## Description:

Currently, the progress bar gets updated by a random number generator each time the app renders, the progress button should allow the user to update the progress bar. This should be accomplished from the front-end due to working with a limited external API.

## Task:

- [ ] Create a new property for each book, "Chapters", and assign a value of a random number.
- [ ] Create a new property for each book, "Current Chapter", and assign 1 as the default value.
- [ ] Create a counter, each time the user clicks "Update Progress" the "Current Chapter" value should increment by 1, and the UI should get updated.
- [ ] Refactor "progress" property to receive store the percentage value of the progress. (Current Chapter / Total Chapters) * 100.
